- name: Install Apache
  ansible.builtin.apt:
      name: apache2
      state: present
  when: ansible_os_family == "Debian"

- name: Ensure Apache is started and enabled
  ansible.builtin.service:
    name: "{{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2' }}"
    state: started
    enabled: yes

- name: Copy custom index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html

- name: Restart Apache
  ansible.builtin.service:
    name: "{{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2' }}"
    state: restarted