---
plugin: aws_ec2
regions:
  - us-east-1
filters:
  instance-state-name: running
keyed_groups:
  - key: tags.Name
compose:
  ansible_host: public_ip_address if public_ip_address is defined else private_ip_address