---
- name: Set up Apache
  hosts:
    - _apache_instance_1
    - _apache_instance_2
  become: true
  vars_files:
    - inventory/group_vars/all/vault.yml
  roles:
    - apache
    
- name: Set up HAProxy
  hosts:
    - _ha_proxy_lb
  become: true
  vars_files:
    - inventory/group_vars/all/vault.yml
  roles:
    - haproxy